language: r

os:
  - linux
  - osx

r_packages:
  - devtools
  - tidyverse
  - covr

apt_packages:
  - libboost-graph-dev
  - libgit2-dev

cache: packages

after_success:
  - Rscript -e 'library(covr); codecov()'
