language: r

r_packages:
  - covr

r_binary_packages:
  - later
  - tidyverse
  - devtools

apt_packages:
  - libboost-graph-dev
  - libgit2-dev

before_install:
  - cd R_package

after_success:
  - Rscript -e 'library(covr); codecov("R_package")'
