language: r

r_packages:
  - devtools
  - tidyverse
  - covr

apt_packages:
  - libboost-graph-dev
  - libgit2-dev

cache: packages

jobs:
  allow_failures:
    - os: windows
  include:
  - r: release
    name: "Linux CRAN build"
    if: commit_message =~ /(RC)/
    os: linux
    before_script: export NOT_CRAN=false
    script:
      - R CMD build .
      - R CMD check *tar.gz --as-cran
    after_success:
      - Rscript -e 'library(covr); codecov(flags = "cran")'
  - r: release
    name: "OSX CRAN build"
    if: commit_message =~ /(RC)/
    os: osx
    before_script: export NOT_CRAN=false
    script:
      - R CMD build .
      - R CMD check *tar.gz --as-cran
    after_success:
      - Rscript -e 'library(covr); codecov(flags = "cran")'
  - language: shell
    name: "Windows CRAN build"
    os: windows
    before_script:
      - choco install -y r.project
      - export R_VERSION=`ls 'C:\Program Files\R\'`
      - export PATH=$PATH:';C:\Program Files\R\'$R_VERSION'\bin\x64\'
      - echo 'options(repos = "https://cloud.r-project.org", install.packages.compile.from.source = "never")' > ~/.Rprofile.site
      - export R_PROFILE=~/.Rprofile.site
      - export NOT_CRAN=false
      - echo $PATH
      - Rscript.exe -e 'install.packages("devtools", dependencies = TRUE)'
      - Rscript.exe -e 'd <- devtools::dev_package_deps(dependencies = TRUE); install.packages(d$package, dependencies = TRUE)'
    script:
      - R.exe CMD build .
      - R.exe CMD check *tar.gz --as-cran
    after_success:
      - Rscript.exe -e 'library(covr); codecov(flags = "cran")'
  - r: release
    name: "Linux full Test and Coverage"
    os: linux
    script:
      - cp -r extra_data/qr_trace inst/extdata/
      - R CMD build .
      - R CMD check *tar.gz --as-cran
    after_success:
      - Rscript -e 'Sys.setenv(NOT_CRAN = "true"); library(covr); codecov()'
