language: r

r_packages:
  - covr
  - devtools

r_binary_packages:
  - later
  - tidyverse

apt_packages:
  - libboost-graph-dev

before_install:
  - cd R_package

after_success:
  - Rscript -e 'library(covr); codecov("R_package")'
