language: r

r_packages:
  - devtools
  - tidyverse
  - covr

apt_packages:
  - libboost-graph-dev
  - libgit2-dev

cache: packages

before_install:
  - cd R_package

after_success:
  - Rscript -e 'library(covr); codecov()'
