language: r

r_packages:
  - devtools
  - tidyverse
  - covr

apt_packages:
  - libboost-graph-dev
  - libgit2-dev

cache: packages

jobs:
  include:
  - r: release
    name: "Linux CRAN build"
    os: linux
    before_script: export NOT_CRAN=false
    script:
      - R CMD build .
      - R CMD check *tar.gz --as-cran
    after_success:
      - Rscript -e 'library(covr); codecov()'
  - r: release
    name: "OSX CRAN build"
    os: osx
    before_script: export NOT_CRAN=false
    script:
      - R CMD build .
      - R CMD check *tar.gz --as-cran
    after_success:
      - Rscript -e 'library(covr); codecov()'
  - r: release
    name: "Linux full Test and Coverage"
    os: linux
    script:
      - cp -r extra_data/qr_trace inst/extdata/
      - R CMD build .
      - R CMD check *tar.gz --as-cran
    after_success:
      - Rscript -e 'Sys.setenv(NOT_CRAN = "true"); library(covr); codecov()'
