language: r

r_packages:
  - devtools
  - tidyverse
  - covr

apt_packages:
  - libboost-graph-dev
  - libgit2-dev

cache: packages

jobs:
  allow_failures:
    - os:
      - windows
      - osx
  include:
  - r: release
    name: "Linux CRAN build"
    if: commit_message =~ /^.*\(test\)$/
    os: linux
    before_script: export NOT_CRAN=false
    script:
      - R CMD build .
      - R CMD check *tar.gz --as-cran
    after_success:
      - Rscript -e 'library(covr); codecov(flags = "fast")'
  - r: release
    name: "OSX CRAN build"
    if: commit_message =~ /^.*\(test\)$/
    os: osx
    before_script: export NOT_CRAN=false
    script:
      - R CMD build .
      - R CMD check *tar.gz --as-cran
    after_success:
      - Rscript -e 'library(covr); codecov(flags = "fast")'
  - language: shell
    name: "Windows CRAN build"
    if: commit_message =~ /^.*\(test\)$/
    os: windows
    before_script:
      - choco install -y r.project
      - choco install rtools
      - export R_VERSION=`ls 'C:\Program Files\R\'`
      - export PATH='C:\Program Files\R\'$R_VERSION'\bin\x64\':$PATH
      - echo 'options(repos = "https://cloud.r-project.org", install.packages.compile.from.source = "never")' > ~/.Rprofile.site
      - export R_PROFILE=~/.Rprofile.site
      - export NOT_CRAN=false
      - export PATH='C:\rtools40\usr\bin\;':$PATH
      - echo $PATH
      - ls 'C:\rtools40\'
      - Rscript.exe -e 'install.packages("devtools", dependencies = TRUE)'
      - Rscript.exe -e 'deps <- devtools::dev_package_deps(dependencies = TRUE); inst <- installed.packages(); install.packages(deps$package[!deps$package %in% inst[,"Package"]])'
    script:
      - R.exe CMD build .
      - R.exe CMD check *tar.gz --as-cran --no-manual --install-args=--build
    after_failure:
      - cat 'C:/Users/travis/build/schnorr/starvz/starvz.Rcheck/00install.out'
      - cat 'C:/Users/travis/build/schnorr/starvz/starvz.Rcheck/00check.log'
    after_success:
      - Rscript.exe -e 'library(covr); codecov(flags = "fast")'
  - r: release
    name: "Linux full Test and Coverage"
    os: linux
    script:
      - cp -r extra_data/qr_trace inst/extdata/
      - R CMD build .
      - R CMD check *tar.gz --as-cran
    after_success:
      - Rscript -e 'Sys.setenv(NOT_CRAN = "true"); library(covr); codecov()'
