
coverage:
  status:
    project:
      default:
        # basic
        target: auto
        threshold: 5%
    patch: off

require_ci_to_pass: no
notify:
  wait_for_ci: yes

flags:
  fast:
    joined: false
